version: "3"

services:
    api:
        image: ${DOCKER_USERNAME}/jobpt:api
        ports:
            - "8000:8000"
        environment:
            - OPENAI_API_KEY=${OPENAI_API_KEY}
        volumes:
            - ./data:/app/data

    web:
        image: ${DOCKER_USERNAME}/jobpt:web
        ports:
            - "7860:7860"
        environment:
            - OPENAI_API_KEY=${OPENAI_API_KEY}
        volumes:
            - ./ui:/app/ui
            - ./data:/app/data
