version: "3"

services:
    api:
        image: ${DOCKER_USERNAME}/jobpt:api
        network_mode: "host"
        environment:
            - OPENAI_API_KEY=${OPENAI_API_KEY}
        volumes:
            - ./data:/app/data

    web:
        image: ${DOCKER_USERNAME}/jobpt:web
        network_mode: "host"
        volumes:
            - ./data:/app/data
